name: Build Angular and copy to ky-niem-web

on:
  push:
    branches:
      - main
      - profile
jobs:
  deploy-memory:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Install dependencies
        run: cd ./ky-niem-web && npm install --force

      - name: ğŸ”¨ Build Angular
        run: cd ./ky-niem-web && npm run build -- --output-path=dist --base-href=/memories/

      - name: ğŸ“ Copy build to ky-niem-web/
        run: rm -rf ./memories && mkdir memories && cd ./ky-niem-web && cp -r dist/* ../memories

      - name: Push to GitHub Pages
        run: |
          git config --global user.name "Hbs"
          git config --global user.email "Hbs@memories.io"
          git add -f memories
          git commit -a -m "Deploy changes"
          git remote set-url origin https://$token@github.com/hbslovely/hbslovely.github.io.git
          git push origin main
        env:
          token: ${{ secrets.GH_PAT }}

  deploy-profile:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Install dependencies
        run: cd ./my-working-profile && npm install --force

      - name: ğŸ”¨ Build Angular
        run: cd ./my-working-profile && npm run build -- --output-path=dist --base-href=/profile/

      - name: ğŸ“ Copy build to profile/
        run: rm -rf ./profile && mkdir cv && cd ./my-working-profile && cp -r dist/* ../cv

      - name: Push to GitHub Pages
        run: |
          git config --global user.name "Bhn"
          git config --global user.email "Bhn@memories.io"
          git add -f cv
          git commit -a -m "Deploy profile changes"
          git remote set-url origin https://$token@github.com/hbslovely/hbslovely.github.io.git
          git push origin main
        env:
          token: ${{ secrets.GH_PAT }}